Farm 12 updating footer
WildCodeSchool/2103-lille-js-p3-farmconnect-frontend pull request #10
Opened 2021-06-09 17:55 UTC by AntoineCAU

Styling the footer of the website (and little thing on the header to stay coherent

2021-06-09 18:03 UTC, Erriep approved these changes, later dismissed

2021-06-11 11:34 UTC, LoicBrassart requested changes
Noooooope I said

2021-06-11 11:34 UTC, LoicBrassart commented on package.json
> +    "nodemon": "^2.0.7",
Nope

2021-06-14 08:17 UTC, Erriep approved these changes

2021-06-14 09:39 UTC, LoicBrassart approved these changes
NmE!

2021-06-14 09:40 UTC, merged