Farm 13 home update
WildCodeSchool/2103-lille-js-p3-farmconnect-frontend pull request #11
Opened 2021-06-09 20:38 UTC by AntoineCAU

Styling with love on the Home component

2021-06-09 20:58 UTC, Erriep approved these changes, later dismissed

2021-06-11 12:35 UTC, LoicBrassart requested changes
Nopenope

2021-06-11 12:35 UTC, LoicBrassart commented on package.json
> +    "nodemon": "^2.0.7",
Naaaaaaaaaaaaaaaaan! >_<

2021-06-14 08:17 UTC, Erriep approved these changes, later dismissed

2021-06-14 09:40 UTC, LoicBrassart approved these changes, later dismissed
NmE!

2021-06-14 09:46 UTC, Erriep approved these changes, later dismissed

2021-06-14 10:23 UTC, Erriep approved these changes

2021-06-14 10:25 UTC, LoicBrassart approved these changes
SnE!

2021-06-14 10:26 UTC, merged