Farm 21 security password
WildCodeSchool/2103-lille-js-p3-farmconnect-frontend pull request #19
Opened 2021-06-17 10:48 UTC by Erriep

2021-06-17 12:19 UTC, AntoineCAU approved these changes, later dismissed

2021-06-17 14:47 UTC, LoicBrassart approved these changes
SnE!

2021-06-18 06:34 UTC, LoicBrassart requested changes
Evils to Fix

2021-06-18 06:34 UTC, LoicBrassart commented on src/components/Registration/index.jsx
> +    axios.post('http://localhost:5050/auth/signup', users);
Don't use a hardcoded "http://localhost", it won't work in production
Time to use Dotenv !

2021-06-18 06:34 UTC, LoicBrassart commented on src/components/Registration/index.jsx
> +              type="text"
**Why** would you want to do that on a registration form ? :fearful:

2021-06-22 09:30 UTC, AntoineCAU approved these changes

2021-06-22 11:03 UTC, LoicBrassart approved these changes
SnE!

2021-06-22 11:32 UTC, merged