adding NavBar in the header
WildCodeSchool/2103-lille-js-p3-farmconnect-frontend pull request #3
Opened 2021-06-02 13:00 UTC by AntoineCAU

Creating NavBar links in the Header component

2021-06-02 13:04 UTC, Erriep requested changes
Change Contact to contact on the link route.

2021-06-02 13:06 UTC, Erriep submitted a review, later dismissed

2021-06-02 15:49 UTC, LoicBrassart requested changes
Plz fix Evil!

2021-06-02 15:49 UTC, LoicBrassart commented on src/components/Header/index.jsx
> +    <Router>
Your `<Router>` should be in the root `index.js` file
(Right now, **only** your Header benefits from the Router, not the whole app)

2021-06-02 19:33 UTC, Erriep approved these changes, later dismissed

2021-06-03 08:26 UTC, Erriep approved these changes, later dismissed

2021-06-03 08:29 UTC, Erriep approved these changes

2021-06-04 10:55 UTC, LoicBrassart approved these changes
SnE!

2021-06-04 10:57 UTC, merged