Farm 40 use context for user & add myservice app fav
WildCodeSchool/2103-lille-js-p3-farmconnect-frontend pull request #30
Opened 2021-07-07 12:58 UTC by Erriep

2021-07-07 13:03 UTC, AntoineCAU approved these changes, later dismissed

2021-07-08 07:58 UTC, LoicBrassart requested changes
One console.log to remove

2021-07-08 07:58 UTC, LoicBrassart commented on src/components/Login/index.jsx
> +        console.log(setUser);
Plz remove console.log

2021-07-08 08:18 UTC, AntoineCAU approved these changes

2021-07-08 08:29 UTC, LoicBrassart approved these changes
NmE!

2021-07-08 08:31 UTC, merged