Farm 35 creation page cockpit
WildCodeSchool/2103-lille-js-p3-farmconnect-frontend pull request #35
Opened 2021-07-09 13:30 UTC by AntoineCAU

2021-07-10 14:44 UTC, Erriep approved these changes, later dismissed

2021-07-12 07:38 UTC, LoicBrassart requested changes
Use Links instead of buttons

2021-07-12 07:38 UTC, LoicBrassart commented on src/components/Cockpit/index.jsx
> +          </button>
Why not use a <Link> ?

2021-07-12 07:38 UTC, LoicBrassart commented on src/components/Cockpit/index.jsx
> +            >
Why not use a <Link> ?

2021-07-12 09:58 UTC, Erriep approved these changes

2021-07-13 07:22 UTC, LoicBrassart approved these changes
SnE

2021-07-13 07:25 UTC, merged