ajout du composant Home
WildCodeSchool/2103-lille-js-p3-farmconnect-frontend pull request #4
Opened 2021-06-02 13:54 UTC by Gasparddhi

A valider et a remplacé my profil par Home

2021-06-02 13:55 UTC, Erriep approved these changes

2021-06-02 19:21 UTC, Erriep submitted a review, later dismissed

2021-06-04 10:56 UTC, LoicBrassart submitted a review, later dismissed
SnE!

2021-06-07 07:51 UTC, Erriep approved these changes, later dismissed

2021-06-07 07:55 UTC, Erriep submitted a review, later dismissed

2021-06-07 09:50 UTC, LoicBrassart requested changes
Nope!
More style, and more Evils! è_é

2021-06-07 09:50 UTC, LoicBrassart commented on src/components/Home/styles.jsx
> + }
Where's my Prettier ?! :x:

2021-06-07 09:50 UTC, LoicBrassart commented on src/components/Home/styles.jsx
> +      font-family: Verdana;
For the whole file, I want you to fix your indentations

2021-06-09 08:09 UTC, Erriep approved these changes

2021-06-09 08:41 UTC, LoicBrassart approved these changes
SnE!

2021-06-09 08:46 UTC, merged