update mycockpit myapps myprofil
WildCodeSchool/2103-lille-js-p3-farmconnect-frontend pull request #44
Opened 2021-07-17 21:52 UTC by Erriep

2021-07-17 21:54 UTC, Erriep commented
fixed bug on the page when user don't exist and screen a box to link on login connect

2021-07-19 06:36 UTC, AntoineCAU approved these changes, later dismissed

2021-07-19 07:09 UTC, LoicBrassart requested changes
Evils to fix !

2021-07-19 07:09 UTC, LoicBrassart commented on src/components/Cockpit/index.jsx
> +  }
You should reverse this: _When my component is mounted, if `user` is not `null`, then blablabla_

2021-07-19 07:09 UTC, LoicBrassart commented on src/components/MyApps/index.jsx
> +  }
Same

2021-07-19 07:09 UTC, LoicBrassart commented on src/components/MyProfile/index.jsx
> +  }
Same

2021-07-19 07:09 UTC, LoicBrassart commented on src/components/MyProfile/index.jsx
> +                      }}
May I know why these styles are not elsewhere ?

2021-07-19 09:30 UTC, AntoineCAU approved these changes
SnE

2021-07-19 10:08 UTC, LoicBrassart approved these changes
NmE

2021-07-19 10:13 UTC, merged