Farm 50 global style
WildCodeSchool/2103-lille-js-p3-farmconnect-frontend pull request #47
Opened 2021-07-19 17:51 UTC by AntoineCAU

2021-07-19 18:23 UTC, Erriep approved these changes, later dismissed

2021-07-20 07:20 UTC, Erriep submitted a review, later dismissed

2021-07-20 08:19 UTC, LoicBrassart commented
I was reviewing when you added your last commit @AntoineCAU -_-

2021-07-22 09:52 UTC, LoicBrassart requested changes
Fix these plz

2021-07-22 09:52 UTC, LoicBrassart commented on src/components/Cockpit/index.jsx
> +                N’hésitez pas à nous contacter pour nous dire ce que vous pensez
This didn't pass through Prettier/ESLint

2021-07-22 09:52 UTC, LoicBrassart commented on src/components/Contact/index.jsx
> +                disabled={!handleSubmit}
`handleSubmit` is a function -> it's always true

2021-07-26 07:43 UTC, Erriep commented
Resolve conflits

2021-07-26 08:04 UTC, Erriep approved these changes

2021-07-26 08:17 UTC, LoicBrassart approved these changes
SnE

2021-07-26 08:38 UTC, merged