Farm 53 add exploitation
WildCodeSchool/2103-lille-js-p3-farmconnect-frontend pull request #50
Opened 2021-07-26 09:00 UTC by Erriep

2021-07-26 09:01 UTC, AntoineCAU submitted a review, later dismissed

2021-07-26 09:36 UTC, LoicBrassart requested changes
Please be more careful while adding last-minute features to this project

2021-07-26 09:36 UTC, LoicBrassart commented on src/components/AddExploitation/index.jsx
> +  const [datas, setDatas] = useState();
Always give an initial value, if only to be sure the variable has the right type right off the bat

2021-07-26 09:36 UTC, LoicBrassart commented on src/components/AddExploitation/index.jsx
> +  };
... Wait, what ?

2021-07-26 09:36 UTC, LoicBrassart commented on src/components/MyProfile/index.jsx
> +        console.log(exploitUser);
Nope, still no `console.log`

2021-07-26 13:37 UTC, AntoineCAU approved these changes

2021-07-27 08:54 UTC, LoicBrassart approved these changes
One minor typo

2021-07-27 08:54 UTC, LoicBrassart commented on src/components/MyProfile/index.jsx
> +  const [exploitUser, setExloitUser] = useState([]);
Typo in the function's name

2021-07-27 09:07 UTC, merged