Basic Restructuration
WildCodeSchool/2103-lille-js-p3-farmconnect-frontend pull request #8
Opened 2021-06-09 13:41 UTC by AntoineCAU

Basic Restructuration !

2021-06-09 13:46 UTC, Erriep approved these changes, later dismissed
Good job !

2021-06-09 14:32 UTC, Erriep submitted a review, later dismissed

2021-06-09 14:36 UTC, Erriep submitted a review, later dismissed

2021-06-11 11:26 UTC, LoicBrassart requested changes
Stop trying to use `nodemon` in your frontend app

2021-06-11 11:26 UTC, LoicBrassart commented on package.json
> +    "dev": "nodemon server.js",
Not in the frontend, nope

2021-06-11 11:26 UTC, LoicBrassart commented on package.json
> +    "nodemon": "^2.0.7",
Not in the frontend, nope

2021-06-14 08:18 UTC, Erriep submitted a review, later dismissed

2021-06-14 09:35 UTC, LoicBrassart approved these changes, later dismissed
NmE!

2021-06-14 09:43 UTC, Erriep approved these changes

2021-06-14 09:47 UTC, LoicBrassart approved these changes
SnE!

2021-06-14 09:54 UTC, merged