Farm 01 form login
WildCodeSchool/2103-lille-js-p3-farmconnect-frontend pull request #9
Opened 2021-06-09 14:56 UTC by CaroD59

Login Form modified

2021-06-09 18:14 UTC, Erriep requested changes

2021-06-09 18:14 UTC, Erriep commented on src/components/Login/index.jsx
> +      <img src="./Images/FC.png" alt="" className="FarmConnectLogo" />
Change "Images" folder to "img"

2021-06-10 06:46 UTC, Erriep approved these changes, later dismissed

2021-06-11 11:26 UTC, LoicBrassart commented
Solve conflicts first plz

2021-06-11 12:12 UTC, Erriep approved these changes

2021-06-11 12:37 UTC, LoicBrassart approved these changes
SnE!

2021-06-11 13:46 UTC, merged